services:
  node:
    build: .
    command: >
      sh -c "python run_node.py --name ${HOSTNAME} --tcp-port 6001 2>&1 | tee /app/logs/${HOSTNAME}.log"
    networks:
      - swarmlink_net
    volumes:
      - ./logs:/app/logs

  api:
    build: .
    command: >
      sh -c "uvicorn api:app --host 0.0.0.0 --port 8000 2>&1 | tee /app/logs/api.log"
    environment:
      SWARMLINK_NODE_NAME: api-node
      SWARMLINK_TCP_PORT: 6010
    ports:
      - "8000:8000"
    networks:
      - swarmlink_net
    volumes:
      - ./logs:/app/logs

networks:
  swarmlink_net:
    driver: bridge
