[project]
name = "SwarmLink"
version = "0.1.0"
description = "Application to share data and view videos with your friends"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=26.1.0",
    "prettier>=0.0.7",
]
